"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.produtosRoutes = void 0;
var Express = require("express");
var ProdutoController_1 = require("../controllers/ProdutoController");
var funcionalidadesValidacao = require('../modules/funcionalidadesValidacao').funcionalidadesValidacao;
var checkAuth = require('../modules/tokenValidation').checkAuth;
var moment = require("moment");
exports.produtosRoutes = Express.Router();
exports.produtosRoutes.get('/dashboard', checkAuth, ProdutoController_1.ProdutosController.dashboard);
exports.produtosRoutes.get('/estoque', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.estoque);
exports.produtosRoutes.get('/estoque/:page', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.estoque);
exports.produtosRoutes.get('/cadastrar-produto', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.cadastrarProduto);
exports.produtosRoutes.post('/cadastrar-produto', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.cadastrarProdutoPost);
exports.produtosRoutes.get('/editar-produto/:id', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.editarProduto);
exports.produtosRoutes.post('/editar-produto', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.editarProdutoPost);
exports.produtosRoutes.post('/baixa-produto', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.baixaProduto);
exports.produtosRoutes.post('/remover-produto', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.removerProduto);
exports.produtosRoutes.get('/arquivos/planilha', checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.exportarPlanilha);
exports.produtosRoutes.get("/arquivos/relatorio-".concat(moment().format("DD-MM-YYYY")), checkAuth, funcionalidadesValidacao, ProdutoController_1.ProdutosController.exportarRelatorio);
